### ISSUE TITLE
How to calculate weights?

### ISSUE THREAD

**Issue by sumeetmathpati** [arvind-rs/phishing_detector#1]
Hello, I am new to ML, hence sorry if you think this question is stupid.

But can you tell me how did you computed those weights in [content.js](https://github.com/arvind-rs/phishing_detector/blob/4805ed2729fc1075de40efed75e1b0e3c937ab77/Engineering%20Module/content.js#L6) file?

**Comment by MohammedYusuf-123** [comment]
hi did you find the answer for using the weights in content.js

**Comment by sumeetmathpati** [comment]
What do you mean by "using weights"? I found out how to get those values form python code output.

**Comment by MohammedYusuf-123** [comment]
how?

**Comment by sumeetmathpati** [comment]
Just see [this](https://github.com/sumeetmathpati/phishing_detector/blob/master/ML%20Algorithm%20Evaluation/run_algorithms.py) file. I've added print statements in this file to print those weights.

**Comment by MohammedYusuf-123** [comment]
thanks now i am able to see the weights. but after using linear kernel the accuracy is decreasing.
and can you explain what is the role of the Target_Labels.csv file

**Comment by MohammedYusuf-123** [comment]
i am not getting this one thing about Target_Labels.csv file

**Comment by sumeetmathpati** [comment]
The're the classes showing if the URL is malicious or not.

**Comment by MohammedYusuf-123** [comment]
how are they created?
